In [2]:
import numpy as np


In [3]:
matrix=np.array([[568.25,241.684,39.432],[24.553,59.532,954.25664],[27.156,66.54,91.656]])

In [4]:
matrix

array([[568.25   , 241.684  ,  39.432  ],
       [ 24.553  ,  59.532  , 954.25664],
       [ 27.156  ,  66.54   ,  91.656  ]])

In [5]:
matrix=np.array([[568.25,241.684,39.432],[24.553,59.532,954.25664],[27.156,66.54,91.656]])

In [6]:
def power_method(A):
    arr=np.array(A)
    n,m=np.shape(A)
    x=np.random.rand(m)
    while True:
        v=np.matmul(matrix,x)
        norm=np.linalg.norm(v)
        x_new=v/np.linalg.norm(v)
        if np.linalg.norm(x-x_new)<0.01:
            break
        x=x_new
    return x
    

In [7]:
x=power_method(matrix)

In [8]:
x

array([0.98061007, 0.18064713, 0.07596379])

In [9]:
def qr(A):
    rand=np.random.randn(*np.shape(A))
    Q,_=np.linalg.qr(A)
    i=0
    while True:
        i=i+1
        Z=A.dot(Q)
        Q_new,R_new=np.linalg.qr(Z)
        if np.linalg.norm(Q_new-Q)<0.0001:
            break
        if i==10000:
            break
        Q=Q_new
    return R_new, Q
        
        
        
    

In [10]:
qr(matrix)

(array([[ 612.78446943,  188.76191665, -119.40042051],
        [   0.        ,  270.91304844, -886.25062186],
        [   0.        ,    0.        , -164.21393037]]),
 array([[-0.98288208,  0.18222329, -0.02715668],
        [-0.1692311 , -0.95123774, -0.25789067],
        [-0.07282615, -0.24888037,  0.96579238]]))

In [11]:
np.linalg.eig(matrix)

(array([ 612.784479  ,  270.88465892, -164.23113792]),
 array([[-0.98288207, -0.63457219,  0.296039  ],
        [-0.16923114,  0.75096949, -0.93161614],
        [-0.07282616,  0.18265532,  0.2108371 ]]))

In [12]:
def simultaneous_power_iteration(A, k):
    n, m = A.shape
    Q = np.random.rand(n, k)
    Q, _ = np.linalg.qr(Q)
    Q_prev = Q
 
    for i in range(1000):
        Z = A.dot(Q)
        Q, R = np.linalg.qr(Z)

        # can use other stopping criteria as well 
        err = ((Q - Q_prev) ** 2).sum()
        if i % 10 == 0:
            print(i, err)

        Q_prev = Q
        if err < 1e-3:
            break

    return R, Q

In [13]:
simultaneous_power_iteration(matrix,2)

0 1.4057780159292819
10 0.0008147000453053166


(array([[612.84142558, 190.74836497],
        [  0.        , 286.91703285]]),
 array([[-0.98285758,  0.18206249],
        [-0.16935903, -0.95385105],
        [-0.07285938, -0.2387916 ]]))

In [2]:
###########House Holder Transform##########################
import numpy as np

In [12]:
matrix=np.array([[1,8,3,4],[2,3,4,5]])
n,m=np.shape(matrix)
print(m,n)
matrix[:,0]

4 2


array([1, 2])

In [215]:
def hht(arr,index,column):
    matrix=np.array(arr)
    n,m=np.shape(matrix)
    j=index-1
    column=column-1
    alpha=np.sqrt(np.sum(matrix[:,j]*matrix[:,j]))*np.sign(matrix[j,column])*np.array([-1])
    r=np.sqrt(0.5*alpha*alpha-0.5*matrix[j,column]*alpha)
    w0=(matrix[j,column]-alpha)/(2*r)
    wj=np.array([matrix[i,0]*0.5/r for i in range(1,n-j)])
    w=np.array(np.concatenate((w0,np.squeeze(wj))))
    P=np.identity(n-j)-2*np.outer(w,w)
    matrix_1=np.matmul(P,matrix)
    return alpha,r ,w, matrix_1
    

In [216]:
big=np.random.normal(size=(5,7))*20
big=np.array([[4, 1 , -2, 2],
[1 ,2 ,0 ,1],
[-2 ,0, 3, -2],
[2 ,1 ,-2 ,-1]])

In [217]:
np.sum(big[:,0])

5

In [218]:
a,r,w,P=hht(big,1,1)
print(a,r,w)
print(P)

[-5.] [4.74341649] [ 0.9486833   0.10540926 -0.21081851  0.21081851]
[[-5.00000000e+00 -1.60000000e+00  3.60000000e+00 -2.20000000e+00]
 [ 2.77555756e-17  1.71111111e+00  6.22222222e-01  5.33333333e-01]
 [-2.77555756e-17  5.77777778e-01  1.75555556e+00 -1.06666667e+00]
 [ 0.00000000e+00  4.22222222e-01 -7.55555556e-01 -1.93333333e+00]]


In [ ]:
[-5.00000000e+00 -1.60000000e+00  3.60000000e+00 -2.20000000e+00]
 [ 2.77555756e-17  1.71111111e+00  6.22222222e-01  5.33333333e-01]
 [-2.77555756e-17  5.77777778e-01  1.75555556e+00 -1.06666667e+00]
 [ 0.00000000e+00  4.22222222e-01 -7.55555556e-01 -1.93333333e+00]]


In [ ]:
for i in range(0)